### ISSUE TITLE
Add GitHub Actions Workflow for Testing and Branch Protection

### ISSUE THREAD

**Issue by NiCrook** [NiCrook/practice-certification-exams#7]
# **Description:**
We need to implement a GitHub Actions workflow that automatically runs tests on newly pushed branches and pull requests. This will ensure that tests are executed for every change and that only branches or pull requests that pass all tests can be merged into the `main` branch. This will help maintain code quality and prevent broken code from being merged.

## **Expected Behavior:**
- A GitHub Actions workflow is triggered on new branches and pull requests to run tests.
- The workflow status (pass/fail) should be reflected in the pull request interface.
- Pull requests with failing tests should be blocked from being merged into the `main` branch until they pass.

## **Steps to Reproduce:**
1. Create a new branch or open a pull request with changes.
2. Observe that the new GitHub Actions workflow should trigger and run the defined tests.
3. Check the status of the workflow in the pull request interface.
4. Verify that pull requests with failing tests cannot be merged into the `main` branch.

## **Proposed Solution:**
- **Create a GitHub Actions Workflow File:**
  - Define a workflow file in `.github/workflows/` that runs on `push` and `pull_request` events.
  - Configure the workflow to install dependencies, run tests, and report results.
- **Set Up Branch Protection Rules:**
  - Configure the `main` branch to require status checks to pass before merging.
  - Ensure that the workflow status is included in the required status checks for the `main` branch.
- **Example Workflow File (`.github/workflows/test.yml`):**
  ```yaml
  name: CI

  on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm test
  ```

### **Additional Context:**
- This workflow will ensure that every branch and pull request is tested before merging.
- Branch protection rules will prevent any failing code from being merged into the main branch, maintaining the stability of the codebase.
- Adjust the workflow configuration based on your project's specific requirements (e.g., language, dependencies, test commands).

### **Tasks:**
- [ ] Create the GitHub Actions workflow file in `.github/workflows/`.
- [ ] Configure the workflow to run tests on push and pull request events.
- [ ] Set up branch protection rules to require passing status checks before merging.
- [ ] Test the workflow and branch protection rules to ensure they work as expected.
- [ ] Update documentation to reflect the new CI/CD setup and branch protection policies.
