### ISSUE TITLE
Create `main.py` File for Command-Line Execution

### ISSUE THREAD

**Issue by NiCrook** [NiCrook/practice-certification-exams#9]
# **Description:**
We need to create a `main.py` file that serves as the entry point for the application. This file will allow users to run the project directly from the terminal by executing `python main.py`. The `main.py` file should handle the initialization and execution of the application's primary functions.

## **Expected Behavior:**
- A `main.py` file is added to the root of the repository.
- The file should serve as the entry point for the application and be executable from the terminal.

## **Proposed Content for `main.py`:**
1. **Import Necessary Modules:**
   - Import modules required for the application to run.

2. **Define Main Function:**
   - Implement the core functionality of the application or call other functions to start the application.

3. **Handle Command-Line Arguments:**
   - Use libraries like `argparse` to parse command-line arguments if needed.

4. **Execution Logic:**
   - Add logic to execute the main functionality of the application when the script is run.

5. **Entry Point Check:**
   - Include an `if __name__ == "__main__":` block to ensure the script can be run directly from the terminal.

## **Example `main.py` Content:**
```python
import argparse
from some_module import start_application  # Import the necessary function or module

def main():
    # Setup command-line argument parsing
    parser = argparse.ArgumentParser(description="Run the application.")
    parser.add_argument('-e', '--exam', type=str, help='Specify the exam to run')
    args = parser.parse_args()
    
    # Example: Start the application
    if args.exam:
        print(f"Starting the exam: {args.exam}")
        start_application(exam_name=args.exam)
    else:
        print("No exam specified. Please provide an exam name.")

if __name__ == "__main__":
    main()
```

### **Additional Context:**
- Having a `main.py` file will simplify running the application from the terminal, making it more user-friendly.
- Ensure the script is well-documented and includes any necessary error handling or usage instructions.

### **Tasks:**
- [ ] Create the `main.py` file in the root of the repository.
- [ ] Implement the core functionality and entry point logic as described.
- [ ] Ensure the script handles command-line arguments if necessary.
- [ ] Test the `main.py` file to verify that it runs correctly from the terminal.
- [ ] Update documentation if needed to reflect the addition of the `main.py` file.
